### ISSUE TITLE
The second companion, the third companion ... And so on are found to be dead in and out of different spaces.

### ISSUE THREAD

**Issue by g818** [Dheuster/AFT-FO4Edition#33]
Hi! Dheuster
 I am confronted with a death problem.
In addition to the first companion who did not mysteriously die, the second companion, the third companion ... And so on are found to be dead in and out of different spaces.
Especially when entering and exiting the loaded space.

i.e. : The second companion or the Nth+1 companion One of them will die and disappear on their own when they enter or leave a loaded space that is not specific.

I set the tool screen as follows [ALL NPC's killable]
<a href="https://imgur.com/XFPX6lG"><img src="https://i.imgur.com/XFPX6lG.jpg" title="source: imgur.com" /></a>
I set ALL NPC's killable up to increase the challenge.

**Comment by Dheuster** [comment]
I would love to fix this issue, but I have to be able to replicate it in order to fix it. I need one of two things. Either a set of instructions I can follow with nothing installed But AFT (and DLC...) that can reliably replicate the issue. Conversly, a save game where nothing was installed other than AFT (And DLC) where the problem is just a load-screen away from happening.

Users often times have trouble getting me these things because many issue are in fact conflicts with other mods. AFT has bug fixes in place to avoid vanilla game bugs that can cause Instant-Death. In this case, I suspect the issue is a conflict with a mod that interfers with AFT's death avoidance bug fix. Mods that change the trade menu or the events associated with the normal trade menu could prevent AFT from fixing/avoiding those vanilla bugs I found (and reported). Or in this case delay death until the next load screen.

See Bug report "Incorrect Stats/Sudden loss of Health": https://www.nexusmods.com/fallout4/mods/26976/?tab=bugs&issue_id=380944

**Comment by g818** [comment]
Replication issue :
The following is a save of two companions (june duncan and athena).  The location is near the Castle High School.
https://drive.google.com/file/d/1tJU9s-O6suEgsFviDv5B-UHiqVitzGYn/view?usp=sharing        save
https://drive.google.com/file/d/1komvBLA1kLld2AN6eM9CQ6xnRqW-p-rI/view?usp=sharing   save

preparation and loadorder
https://pastebin.com/zeivt27G

I'm sorry, but I only do this.
Repeatedly entering and exiting of diamond city market, the Nth+1 companion will have an immediate death and disappear.
So you need to remember the ref ID of the companion and confirm the death status through the code(xx011e14.moveto player or xx0026cf.moveto player).

**Comment by g818** [comment]
<a href="https://imgur.com/XFPX6lG"><img src="https://i.imgur.com/XFPX6lG.jpg" title="source: imgur.com" /></a>
Type: prid 14
           showinventory
got AFT master control 77002e0f

click Nth companion
type: removeperk ##018890

or after fast travel
click Nth companion
type: removeperk ##018890

All get a message:
Item ‘018890’ not found for parameter perk.
Compiled script not saved!

30 times a fast travel of the entering and exiting. In this way, from the Red Rocket Repair station to Diamond City, there was no accident of death and disappearance of the entourage.

20 times a fast travel of the entering and exiting. In this way, from the Water purification plant(super mutants’)  to Diamond City, there was no accident of death and disappearance of the entourage.

I'm so sorry to Dheuster and folks.

I guess when one of the companions appeared in Diamond City, it was descending from a high place, and I didn't know where she was going to die.
When I used the ref ID to find her, she died.

Speculation is based on the water purification plant underground high-space, the follower's instantaneous movement.

**Comment by Dheuster** [comment]
After more investigation, I think this might in fact be AFT. More specifically a bug introduced after the Oct 3rd Bethesda Patch. I suspect the issue is related to outfits. Try using the command above to remove the perk from all followers OR Unmanage the outfits and see if they still die. In my own testing, I found massive health drops when fast travelling into a CITY (Diamond City or Goodneighbor). This invoked the CITY OUTFIT, and it was the gear change that caused the health loss. I'm working on a fix now.

Thanks for reporting this.

**Comment by g818** [comment]
Thank you for your forgiveness and help.
